#!/usr/bin/perl

use strict;
use warnings;

# Path to tasks.json file
my $json_file = "tasks.json";
my $html_file = "tasks.html";

# Read the JSON file manually since we don't have JSON module
open my $json_fh, '<', $json_file or die "Cannot open $json_file: $!";
my $json_text = do { local $/; <$json_fh> };
close $json_fh;

# Simple parsing of JSON for tasks - manual parsing since we don't have JSON module
my $tasks = [];
if ($json_text) {
    # Simple regex-based parsing for demonstration
    while ($json_text =~ /\{[^}]*"id"\s*:\s*(\d+)[^}]*"name"\s*:\s*"([^"]*)"\s*,[^}]*"done"\s*:\s*(true|false)[^}]*\}/g) {
        my $id = $1;
        my $name = $2;
        my $done = ($3 eq 'true') ? 1 : 0;
        push @$tasks, { id => $id, name => $name, done => $done };
    }
}

# Create HTML output
my $html = <<'END_HTML';
<!DOCTYPE html>
<html>
<head>
    <title>TaskCLI - Task List</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            line-height: 1.6;
        }
        h1 {
            color: #333;
            border-bottom: 2px solid #eee;
            padding-bottom: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #f2f2f2;
        }
        tr:hover {
            background-color: #f5f5f5;
        }
        .completed {
            text-decoration: line-through;
            color: #999;
        }
        .status-done {
            color: green;
            font-weight: bold;
        }
        .status-pending {
            color: red;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <h1>TaskCLI - Task List</h1>
END_HTML

$html .= "    <p>Total tasks: " . scalar(@$tasks) . "</p>\n";

$html .= <<'END_TABLE';
    <table>
        <tr>
            <th>ID</th>
            <th>Status</th>
            <th>Task</th>
        </tr>
END_TABLE

# Generate table rows for each task
foreach my $task (@$tasks) {
    my $id = $task->{id};
    my $name = $task->{name};
    # Simple HTML escape - replace special characters
    $name =~ s/&/&amp;/g;
    $name =~ s/</&lt;/g;
    $name =~ s/>/&gt;/g;
    $name =~ s/"/&quot;/g;
    my $done = $task->{done};
    
    my $status_symbol = $done ? "✓" : "✗";
    my $status_class = $done ? "status-done" : "status-pending";
    my $task_class = $done ? "completed" : "";
    
    $html .= "        <tr>\n";
    $html .= "            <td>$id</td>\n";
    $html .= "            <td class=\"$status_class\">$status_symbol</td>\n";
    $html .= "            <td class=\"$task_class\">$name</td>\n";
    $html .= "        </tr>\n";
}

$html .= <<'END_HTML';
    </table>
    <p><small>Generated by TaskCLI on 
END_HTML

# Add the current date and time
my ($sec,$min,$hour,$mday,$mon,$year) = localtime();
$year += 1900;
$mon += 1;
my $date = sprintf("%04d-%02d-%02d %02d:%02d:%02d", $year, $mon, $mday, $hour, $min, $sec);
$html .= "$date</small></p>\n";

$html .= <<'END_HTML';
</body>
</html>
END_HTML

# Write to HTML file
open my $html_fh, '>', $html_file or die "Cannot open $html_file for writing: $!";
print $html_fh $html;
close $html_fh;

print "Tasks exported to $html_file successfully!\n";
